# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m

linters:
  # Use defaults: errcheck, govet, ineffassign, staticcheck, unused
  default: standard

  settings:
    errcheck:
      check-type-assertions: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
