#!/bin/bash
# Generate lint-compliant Homebrew formula for coop
# Usage: ./scripts/generate-formula.sh <version>
#
# This script generates a formula that:
# - Downloads pre-built binaries from GitHub releases
# - Has def install at class level (passes homebrew lint)
# - Supports darwin/linux on arm64/x86_64

set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 <version>" >&2
  exit 1
fi

# Strip leading 'v' if present
VERSION="${VERSION#v}"

REPO="stuffbucket/coop"
RELEASE_URL="https://github.com/${REPO}/releases/download/v${VERSION}"

# Fetch checksums
CHECKSUMS_URL="${RELEASE_URL}/checksums.txt"
echo "Fetching checksums from ${CHECKSUMS_URL}..." >&2
CHECKSUMS=$(curl -sL "$CHECKSUMS_URL")

if [[ -z "$CHECKSUMS" ]]; then
  echo "Error: Could not fetch checksums" >&2
  exit 1
fi

# Extract SHA256 for each platform
# Archive names: coop_<version>_<os>_<arch>.tar.gz
get_sha256() {
  local os="$1"
  local arch="$2"
  echo "$CHECKSUMS" | grep "coop_${VERSION}_${os}_${arch}.tar.gz" | awk '{print $1}'
}

SHA_DARWIN_ARM64=$(get_sha256 "darwin" "aarch64")
SHA_DARWIN_AMD64=$(get_sha256 "darwin" "x86_64")
SHA_LINUX_ARM64=$(get_sha256 "linux" "aarch64")
SHA_LINUX_AMD64=$(get_sha256 "linux" "x86_64")

# Verify we got all checksums
for var in SHA_DARWIN_ARM64 SHA_DARWIN_AMD64 SHA_LINUX_ARM64 SHA_LINUX_AMD64; do
  if [[ -z "${!var}" ]]; then
    echo "Error: Missing checksum for ${var}" >&2
    echo "Available checksums:" >&2
    echo "$CHECKSUMS" >&2
    exit 1
  fi
done

# Generate formula
cat <<EOF
# typed: strict
# frozen_string_literal: true

# This formula was auto-generated by scripts/generate-formula.sh
class Coop < Formula
  desc "AI agent container management with security sandboxing"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${RELEASE_URL}/coop_${VERSION}_darwin_aarch64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
    on_intel do
      url "${RELEASE_URL}/coop_${VERSION}_darwin_x86_64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${RELEASE_URL}/coop_${VERSION}_linux_aarch64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
    on_intel do
      url "${RELEASE_URL}/coop_${VERSION}_linux_x86_64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  def install
    bin.install "coop"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coop --version")
  end
end
EOF
